// Mapeo de íconos organizado en diferentes categorías
const iconMap = {
  languages: {
    JavaScript: 'logos:javascript',
    Python: 'logos:python',
    Go: 'logos:go',
    Ruby: 'logos:ruby',
    Java: 'logos:java',
    CSharp: 'logos:csharp',
    PHP: 'logos:php',
    Rust: 'logos:rust',
    Kotlin: 'logos:kotlin',
    'No Code': 'logos:no-code',
  },
  frameworks: {
    React: 'logos:react',
    Vue: 'logos:vue',
    Angular: 'logos:angular',
    'Node.js': 'logos:nodejs',
    Express: 'logos:express',
    Django: 'logos:django',
    Flask: 'logos:flask',
    FastAPI: 'logos:fastapi',
    Rails: 'logos:rails',
    Spring: 'logos:spring',
    'ASP.NET': 'logos:aspnet',
    Laravel: 'logos:laravel',
    Ktor: 'logos:ktor',
    Rocket: 'logos:rocket',
    Unity: 'logos:unity',
    'no-code': 'logos:no-code',
  },
  databases: {
    MongoDB: 'logos:mongodb',
    MySQL: 'logos:mysql',
    PostgreSQL: 'logos:postgresql',
    SQLite: 'logos:sqlite',
    Redis: 'logos:redis',
  },
  tools: {
    Git: 'logos:git',
    Docker: 'logos:docker-icon',
    VSCode: 'logos:visual-studio-code',
    Postman: 'logos:postman',
    Webpack: 'logos:webpack',
    Figma: 'logos:figma',
  },
};

export default iconMap;
